### ISSUE TITLE
no mention of where to define GPIO pins to use on Pi

### ISSUE THREAD

**Issue by ryantuck** [ManiacalLabs/BiblioPixel#13]
This project is *very* cool. I really want to use it. 

But where in the world do I define which GPIO pins I want to use for data and clock? Or are there set GPIO pins to use depending on LED strip, and if so, what are they, and where would I find them?

**Comment by adammhaile** [comment]
@ryantuck The Pi has set pins for SPI and all the details are laid out here: https://github.com/ManiacalLabs/BiblioPixel/wiki/SPI-Setup

Just note that if you are using the newer models, the GPIO header has more pins. It's pins 19 (Data) and 23 (Clock) instead of 19 and 21 from the older models.

![](http://www.element14.com/community/servlet/JiveServlet/previewBody/73950-102-4-309126/GPIO_Pi2.png)

I will update the documentation shortly since a lot of people probably have the newer models.
