### ISSUE TITLE
Support for APA102 LED

### ISSUE THREAD

**Issue by LeoDJ** [ManiacalLabs/BiblioPixel#14]
I tried all day to implement support for the APA102 LEDs, but I couldn't manage to get it to work...
I even went so far as to change stuff in the led.py file, because the APA102 LED uses a 4-byte (32bit) buffer per LED as stated here (https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/).
But after changing the buffer "generation" code in led.py to support the different buffer structure, the LED strip wasn't only not working correctly as in displaying seemingly random colors from using the StripChannelTest animation, it was now completely dark. That's why I'm starting this issue. I'm just stumped now.
It would be really great if you could implement this or at least give me a hint in the right direction how to implement it myself.

Regards
LeoDJ

**Comment by adammhaile** [comment]
I assume you are doing this from a Raspberry Pi or similar? 
APA102 is on my list for new drivers, but a bit low since support is provided through the [AllPixel](http://maniacallabs.com/AllPixel). But I understand wanting direct support and will try to add it soon.

So, first... and I say this not to be critical but to point you in the right direction. But there's absolutely no need to change led.py

Yes, they use 4 bytes per pixel, but as you can see in the link you included, that extra byte only includes start frame and brightness level (the other 5 bits). So, the way led.py stores the data is perfectly fine. What you need to do is just write a new driver and then in its update() function tack on that extra byte for each pixel.

You should be able to do it pretty easily:

```python
newBuf = [0xE0+brightness]*(self.bufByteCount+self.numLEDs)
newBuf[1::4] = self._buf[0::3]
newBuf[2::4] = self._buf[1::3]
newBuf[3::4] = self._buf[2::3]
self._buf = newBuf
```

This will create a new buffer with the start frame byte inserted before every set of 3 bytes (each pixel). I think that's how the protocol is supposed to work anyways... 
Although, there's one more intricacy that's required for APA102 which I know from writing the AllPixel firmware... it requires some extra empty bytes at the end. The number uses this function: num = (int(self.numLEDs/64.0)+1)

so, you should also do this after the above:

```python
self._buf.extend([0]*(int(self.numLEDs/64.0)+1))
```

That will pad it with the right amount of extra bytes needed to make it all work.
Check out the [Driver Docs](https://github.com/ManiacalLabs/BiblioPixel/wiki/Drivers) regarding writing your own driver... but absolutely not changes to the rest of the library should be required.

If I get a chance in the next day or two, I may just try to do this myself... like I mentioned, it's been on my list for a while now...

**Comment by adammhaile** [comment]
Soo... I couldn't let it stand. The puzzle was too tempting. So I wrote the driver :)
I'll add it to BiblioPixel official after I've had some more time for proper testing, but all you need is below. Enjoy!

Also, be sure everything is setup right by checking out the [SPI Setup docs](https://github.com/ManiacalLabs/BiblioPixel/wiki/SPI-Setup)

```python
from bibliopixel.drivers.spi_driver_base import *

class DriverAPA102(DriverSPIBase):
    """Main driver for APA102 based LED strips on devices like the Raspberry Pi and BeagleBone"""
    
    def __init__(self, num, c_order = ChannelOrder.RGB, use_py_spi = True, dev="/dev/spidev0.0", SPISpeed = 2):
        super(DriverAPA102, self).__init__(num, c_order = c_order, use_py_spi = use_py_spi, dev = dev, SPISpeed = SPISpeed)
           
        #APA102 requires latch bytes at the end
        self._latchBytes = (int(num/64.0)+1)

    def _fixData(self, data):
        gamma = self.gamma
        self._buf = [0 for x in range(self.bufByteCount)]
        for a, b in enumerate(self.c_order):
            self._buf[a:self.numLEDs*3:3] = [gamma[v] for v in data[b::3]]

        newBuf = [0xFF]*(self.bufByteCount+self.numLEDs)
        newBuf[1::4] = self._buf[0::3]
        newBuf[2::4] = self._buf[1::3]
        newBuf[3::4] = self._buf[2::3]
        self._buf = [0,0,0,0] + newBuf
        self._buf.extend([0xFF,0,0,0]*self._latchBytes)



if __name__ == "__main__":
    from bibliopixel.animation import *
    from bibliopixel import *
    import bibliopixel.log as log
    log.setLogLevel(log.DEBUG)

    driver = DriverAPA102(32, c_order=ChannelOrder.BGR, SPISpeed=24)
    led = LEDStrip(driver, threadedUpdate=False)

    try:
        from strip_animations import *
        anim = RainbowCycle(led)
        #anim = StripChannelTest(led)
        anim.run(fps=30)
    except KeyboardInterrupt:
        led.all_off()
        led.update()

```

**Comment by LeoDJ** [comment]
It works like a charm! thank you sooo much!

I thought creating a new buffer and remapping it would be much more complicated :P, that's why I tried to change it in led.py.
Also I'm not that good in Python, I'm more the c++ type ;)

Good work :+1: 

Just two little things I noticed:
1) I had to change the Color order of the APA102 LEDs to BGR, it's is back to front.
2) Where is this "strip_animations" located? Python couldn't find it and I couldn't find it anywhere too.

You did a great job and this library is helping me so much with my current project! (A PoV-Display)

Regards
LeoDJ

**Comment by LeoDJ** [comment]
Okay, nvm, I've found the strip_animations ^^ 
I was just too tired to look in your repo

**Comment by adammhaile** [comment]
Thanks! Glad it's helpful :)
The color ordering is expected and you will see in the example code above from when I posted the driver that I too set it to BGR. However, I have some APA102s that are a different color order... which is why I don't force it to be one channel order in the driver. However... the ones I have that are different are an early revision and I think that all the new ones are the same. So when I release this driver into the main BiblioPixel code I may just change the default in the __init__:

```python
__init__(self, num, c_order = ChannelOrder.BRG, use_py_spi = True, dev="/dev/spidev0.0", SPISpeed = 2):
```

I'm glad you mentioned you were doing POV!! I can help you out there too :)
Check out this: http://maniacallabs.com/2014/11/19/weekend-project-povstick/

But the real thing you want there is the LEDPOV class I made for it :) See below...
Basically, what this does is allow you to run the animation as if it were using LEDMatrix and therefore have full (x,y) coordinates. But when you call update, it allows you to specify how long the frame should last. It divides that by the width of the "matrix" and then splits each vertical line of the image over the strip one at a time until it displays every line. As you can see in the article I linked to above, you can do some really impressive stuff with it... and it was all done on a raspberry pi as well :)

Which reminds me... I really need to put LEDPOV in BiblioPixel as an official thing :)

BTW, if you have any further support questions or just want to show off what you are working on (please do!!) be sure to check out the [Maniacal Labs Forums](http://forum.maniacallabs.com). Before long, we'll probably close down the GitHub issue list and use the forum for all support.

Hope that helps!

```python
#Takes a matrix and displays it as individual columns over time
class LEDPOV(LEDMatrix):
 
    def __init__(self, driver, povHeight, width, rotation = MatrixRotation.ROTATE_0, vert_flip = False):
        self.numLEDs = povHeight * width
 
        super(LEDPOV, self).__init__(driver, width, povHeight, None, rotation, vert_flip, False)
     
    #This is the magic. Overriding the normal update() method
    #It will automatically break up the frame into columns spread over frameTime (ms)    
    def update(self, frameTime = None):
        if frameTime:
            self._frameTotalTime = frameTime
 
        sleep = None
        if self._frameTotalTime:
            sleep = (self._frameTotalTime - self._frameGenTime) / self.width
 
        width = self.width
        for h in range(width):
            start = time.time() * 1000.0
 
            buf = [item for sublist in [self.buffer[(width*i*3)+(h*3):(width*i*3)+(h*3)+(3)] for i in range(self.height)] for item in sublist]
            self.driver.update(buf)
            sendTime = (time.time() * 1000.0) - start
            if sleep:
                time.sleep(max(0, (sleep - sendTime) / 1000.0))
```

**Comment by LeoDJ** [comment]
Wow, that matrix to POV code will be really helpful once the mechanics are done!
I'm just testing the "electrical" possibilities right now, whether I use an Arduino+NRF24 module or just strap the whole RasPi on the moving arm... I don't quite know yet.
I'll definitly keep you updated ;) (I'll be creating a blog for this project soon)

**Comment by adammhaile** [comment]
I highly recommend just using a slip ring for the electrical connection.
That way the controller can stay static.

**Comment by adammhaile** [comment]
Side note: The reason I recommend the slip ring is because using the
wireless module like you mentioned would be far too slow (data rate wise).
You certainly could strap the Pi to it, but then you need batteries and
such... slip ring will simplify it and they are pretty cheap.
