### ISSUE TITLE
There are two different ways to set types of serial LEDs

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#219]
Ran into this while pretending to be a beginner. 

Depending on your specific type of LED, there are two ways to indicate that you are using that LED:

1. Set the `type` in drivers.serial.Serial (as in WS2811).
2. Use a different base class (as in WS2801).

This is not really explained anywhere and will probably confuse people.

**Comment by adammhaile** [comment]
Well... that's two entirely different scenarios.
1) You are using the AllPixel
2) You are using SPI on a Pi or similar.

Since the AllPixel case is identical for all LEDs aside from a few options
this makes sense.
In the SPI case, I could actually now see a use-case for having a driver
just called SPI() and then you giving it an LED type and under the hood it
does all the necessary stuff.
Since we have the SPI base class we kind of do that already so that would
not be hard. To be completely honest, that evolved out of BP originally
just being for the LPD8806, and then adding on other SPI drivers as I went.
THEN the AllPixel came around and things started to get interesting.

Personally, I say we don't change any code and just solve this with better
docs.

Does bring up a question though... In a project for the AllPixel serial
driver, how do you pass in the LEDTYPE value? It's actually an int enum,
but I'm assuming you cannot just put the name in the project file? That
might be a problem... or am I missing something?

**Comment by rec** [comment]
Heh, I have a fix for that last question almost done.  I noticed it after writing this.  Expect a pull request...

---

Regarding the ledtype/type - well, I'm still lost as to the specifics, though this was the same general idea I had.  But you can clear it up in seconds by correcting the following code blocks, particularly the last one...

    # WS2912B drivers - this strip requires no special code.

    # For SPI (e.g. Raspberry Pi)
    driver = DriverSPIBase(num=10, type=LEDTYPE.WS2812B)

    # For AllPixel.  From here: 
    # https://github.com/ManiacalLabs/AllPixel/wiki/Library-Install-and-Strip-Example
    driver = DriverSerial(num=10, type=LEDTYPE.WS2812B)


    # LPD8806 drivers - this strip DOES require special code.

    # For SPI.  There is special code to handle LPD8806 in the class.
    driver = LPD8806(num=10)

    # For AllPixel - *seems wrong* because no special code??
    driver = DriverSerial(num=10, type=LEDTYPE.LPD8806)

**Comment by adammhaile** [comment]
The AllPixel has to know what kinda of LED is connected so it knows what
protocol to switch to. No special code in BP, special code in the AP
firmware.
For now I say leave it as is and maybe change things up in 3.1 or
something. I'm not willing to change this late in the game.

**Comment by rec** [comment]
I'm learning this (almost) entirely so I can document it...

**Comment by adammhaile** [comment]
Cool

**Comment by rec** [comment]
I don't believe that code review really "fixes" this issue, so I'm moving it back to 3.x
