### ISSUE TITLE
Clean up and clear out all __init__.py files

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#231]
Ideally they should all be empy.

**Comment by rec** [comment]
This will result in an API that is not backward compatible with 3.0.x, so we can't do it till 4.0

**Comment by adammhaile** [comment]
Yeah... don't know how you plan to do that without moving a lot of files around since the __init__ files are the only thing keeping the import lengths sane and not 12 levels deep.

**Comment by rec** [comment]
If we want to do any sort of fast startup, this is essential.

Even if you import a subdirectory, this naturally executes bibliopixel/__init__.py, which imports pretty well everything - so splitting up the commands had little effect for small commands. :-/

The ultimate goal will have to be to simply get rid of everything in that file and force people to include specifically what they need, which really isn't that hard.

When we switch to the new version number, we can create a special file bibliopixel/bp.py that duplicates bibliopixel/__init__.py for instant backwards compatibility - if we like.

There really aren't that many levels of module, and people aren't really writing code directly anyway.  

Is it so onerous to write `from bibliopixel.layout.matrix import Matrix` instead of `from bibliopixel import Matrix`?  That's the longest case - and also, the second one is quite ambiguous, as it could be `animation.matrix.Matrix`.
