### ISSUE TITLE
SimPixel.set_layout is trappy.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#232]
[SimPixel.set_layout](https://github.com/ManiacalLabs/BiblioPixel/blob/dev/bibliopixel/drivers/SimPixel/driver.py#L46-L51) doesn't do what it says.

1. It has the side-effect of starting the whole server!
2. If you call it more than once, subsequent calls do nothing and report no error.

**Comment by rec** [comment]
Also, it might or might not start itself on construction, depending on the data passed to it!

**Comment by adammhaile** [comment]
Yeah... all entirely by design, but I was never entirely happy with that. Definitely something for 3.x (even 3.0.x). Will probably rework that as part of the SimPixel recording work. Note: That is NOT the same thing as the BP recording mentioned in the roadmap doc you just sent out. Eventually those may become one... but for now this is purely for the sake of future animation gallery/contest and I plan on having all the recording be SimPixel-side... literally a record button in SimPixel. BP-side recordings would not be helpful as they would probably require BP for playback... yes, we could make SP be able to read the format, but that's for another time. 
One other thought of note, mainly for my future self... right now SimPixel starts getting data at some point, generally less than 20 seconds, after BiblioPixel SP servers starts up. We have auto reconnect but it's never be super fast. I'm tempted to add a way for BP animations to start but effectively pause until SP connects so we can ensure SP gets the whole recording... and yes, I realize this is very much like the "animations can run arbitrarily long" noted in the roadmap, so this would have to be tread lightly upon. I would love to simply add a pause state to BP and utilize that (which could then later be better utilized for aforementioned changes).

**Comment by rec** [comment]
> BP-side recordings would not be helpful

Sure they would.  You could record all the control movements and export them to e.g. a music program.  You could record all the pixels and have a separate program make them into animated GIFs.  You could record a complete sequence on one BP machine and then sent it to another BP machine which didn't even have that animation on it!

:-D

**Comment by adammhaile** [comment]
I didn't mean they won't EVER be helpful. We're totally doing that. I mean that in the context of simply recording SimPixel... though, YES, we could always convert BP-side recordings to something SimPixel likes (or just make SP read the format). I just mean, *right now*, immediate change to SP that would allow recording what you see and uploading it for others to see, so we can do a contest. BP-side recording is too far down the roadmap and SP-side is Easy (TM) in comparison. We want to do a contest for BP 3.0, not 4.0 :)
