### ISSUE TITLE
setup.py develop installs a huge number of things, and has errors (which seem to have no consequences).

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#295]
Do we really need all this cruft for a default install?  What's with the fairly seriously looking errors from jinja?

[develop-errors.txt](https://github.com/ManiacalLabs/BiblioPixel/files/1156879/develop-errors.txt)

It might be necessary but at least we should know that we're doing it.

**Comment by adammhaile** [comment]
Jinja2 is a dependency of Flask which the remote uses as the server/http engine. Though we don't actually use Jinja at all.
And the only reason you see those at all is that you are on Py 3.4 which doesn't support the async syntax: https://stackoverflow.com/questions/43948454/python-invalid-syntax-with-async-def
It installs everything with no errors on 3.5 and 3.6
If it weren't for the Pi I would drop 3.4 support.
This is little more than annoying and maybe a little confusing for anyone on 3.4
I would log a bug with Jinja2... even they say they support Py 3.4 and 3.3 which is obviously not true.
Oh... wait, ugh... the did some janky patching for older versions: https://github.com/pallets/jinja/blob/master/jinja2/asyncsupport.py
Which makes sense now because they support py2 and that obviously has no async. 
Not sure what part of setup.py is flagging that SyntaxError.
