### ISSUE TITLE
`RemoteControl` does too much in its constructor.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#385]
Constructors should avoid doing too many things, particularly setting off threads or other irreversible things.

Now, this is a rule that is made to be broken :-D but in this case it's a problem as we add better error handling and verification.

Our only way to verify a description of an animation (or of a driver or layout) is to construct it.  There's nothing wrong with that, and that works perfect well for all other classes - but for `RemoteControl`, constructing this starts off all this crap long before it should.

We have the `preRun` "virtual" method to override for exactly these sorts of things.  Most of `RemoteControl`'s constructor should be there.

**Comment by adammhaile** [comment]
OK.... so yeah, remote has an incredibly long constructor but
https://github.com/ManiacalLabs/BiblioPixel/blob/8f4a2bab6b94ee96d41c4ba5bdcfe372a49c29df/bibliopixel/remote/control.py#L188
No processes or threads are actually started until preRun or step() is
called. I mean, yeah, I could in theory move stuff into preRun
but there's also the issue that the constructor should fail if you give it
incorrect values. Which is a lot of what that constructor is doing...
checking values, processing the config, all that.

- __init__: check params are valid which may involve minimal processing of
data given and do any setup that can only ever be done once
- preRun: put everything into the "start" state whatever that may mean for
the animation
- step: what happens every frame

Going by that, the only thing that could maybe be moved out of __init__ is
creating the MP queues and the MP process instances (note, they are *not*
started!). That still leaves a lot of param checking, which I have no
intention of ever moving from __init__. It only needs to happen once and
*should* always be checked on class instantiation so that it fails early if
needed.

**Comment by rec** [comment]
ah, hmm!  Perhaps I diagnosed my issue wrong then.  

Something about constructing a list of projects including a remote got me "port number in use" in, seemingly, a constructor, but I'll narrow it down.

---

Sure, at the end of the constructor you should be "ready to run".  Fail as early as possible, even if this involves doing some actual work to verify it.

I'll keep ya posted.

**Comment by adammhaile** [comment]
Oh oh... yeah. The websocket takes a little bit to fully close before it's
available so if you spam creating RemoteControl a bunch of times you'll get
that. Just change the port for each.
