### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#44]
I'm going to file this, even if we close it as "will not fix", just to have a record.

Basically, it isn't too hard to change a Python program to make it support both 2 and 3, using [six](https://pypi.python.org/pypi/six) - a single file solution.

Also, this task can be done "piece at a time" - you don't have to do it all it once or even all of one file at a time.  Of course, you can't fully test it until it's all converted.

The reason to do this is because as a "patriotic" Python developer, I feel bad doing new development in 2 only.

**Comment by adammhaile** [comment]
Agreed. This will be a will not fix for master/dev, but we can tag this as
v3.0 branch only. Will be good to have. The lack of 3 support was orginally
because some dependencies didn't support it, but that's not such an issue
anymore. The main culprit was py-spidev, but v3.0 supports python 3, so
we're good.

**Comment by rec** [comment]
We can support both 2 and 3 in the same codebase, though, so this isn't really a breaking change!

**Comment by adammhaile** [comment]
I realize... but at this point the v2 branch is stable and we have so many
changes planned for v3, that I'd rather just put anything that's not bug
fixes to v2 into the new v3 branch for future release. I might through a
couple new changes into v2 related to some other projects I'm working on,
but only because those projects won't want to wait for v3 to be stable.
