### ISSUE TITLE
loady 1.7.2 issue

### ISSUE THREAD

**Issue by haooken** [ManiacalLabs/BiblioPixel#462]
Seeing this when running bp command on fresh install:

```
C:\Users\cavep>bibliopixel
Traceback (most recent call last):
  File "C:\Python3\Scripts\bibliopixel", line 12, in <module>
    from bibliopixel.main import main
  File "c:\python3\lib\site-packages\bibliopixel\main\main.py", line 12, in <module>
    MODULES = {c: import_symbol('bibliopixel.main.' + c) for c in COMMANDS}
  File "c:\python3\lib\site-packages\bibliopixel\main\main.py", line 12, in <dictcomp>
    MODULES = {c: import_symbol('bibliopixel.main.' + c) for c in COMMANDS}
  File "c:\python3\lib\site-packages\bibliopixel\project\importer.py", line 52, in import_symbol
    result = loady.code.load(typename)
  File "c:\python3\lib\site-packages\loady\code.py", line 69, in load
    return importer.import_code(name, base_path)
  File "c:\python3\lib\site-packages\loady\importer.py", line 70, in import_code
    return candidates[guess_name(names, module_name, typename)]
  File "c:\python3\lib\site-packages\loady\importer.py", line 58, in guess_name
    raise ValueError('No member specified in %s' % fullname)
ValueError: No member specified in bibliopixel.main.alias
```

Removing loady 1.7.2 and replacing with 1.6.6 resolves the problem. Tom is already aware of this and is working on it now (loady 1.7.3 possibly fixes the problem)

**Comment by rec** [comment]
I pushed the fix to loady last night, which seems to fix the issue.  I now have a pull request to fix the consequent breakage in dev.

For the record, here's what happened!

I realized that loady was doing two different things under the same label:

* Loading any any old symbol
* Loading a symbol and then trying to make it executable

In the second case, loady is able to guess that `my_project.my_layout` actually means `my_project.my_layout.MyLayout` and expand that out - but it was only doing that for files loaded from the internet, and it was doing it for _both_ cases.

I split those two cases apart, into `load_code` - which loads something executable using the name guessing trick - and `load_module`, a crappy name which I will fix, which loads any old symbol and doesn't try to do name guessing.  (I can't call it `load_symbol` because that's already used for backwards compatibility with BP...)

I thought I kept backwards compatibility, _but_ in some cases, for code in master, this just wasn't true.
