### ISSUE TITLE
bp help does not show command options

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#556]
You get all the command options if you just run `bp` with nothing, but not with `bp help`

**Comment by rec** [comment]
This puzzled me for a bit because `argparse` shouldn't do that.

But in fact, the problem is obvious from the output.  It thinks that `bp --help` is `bp run --help` because we do some magic to make sure that if there is no command, the default is `bp run`.

I can fix this - I just wanted to document the issue.

**Comment by rec** [comment]
[profanity deleted]

I just wasted ten minutes because - are you ready for this? `argparse.ArgumentParser.parse_args()` _does not necessarily return or throw an exception!_

That's right!  If you have a `--help` argument in there, then that function calls `sys.exit()` instead of returning.  This is probably documented but it's surprising behavior.

Wanted to write this out for future reference!

**Comment by adammhaile** [comment]
Wow... fun times. Good catch.
