### ISSUE TITLE
Add BiblioPixelAnimations to the list of possible directories to resolve animations.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#875]
I want to fix this bug before 3.5, because I think it will make for much more showy documentation/examples.

I really want people to see these tiny clear little Project documents in the first few pages with fancy animations and say - "I could do that!"

So I want a project that looks like this:

    animation: .sequence
      length: 3
      animations: 
        - .matrix.MatrixRain
        - .matrix.SpinningTriangle
        - .matrix.Twinkle

and not

    animation: .sequence
      length: 3
      animations: 
        - BiblioPixelAnimations.matrix.MatrixRain
        - BiblioPixelAnimations.matrix.SpinningTriangle
        - BiblioPixelAnimations.matrix.Twinkle

---

Right now, we use the alias section to get rid of e.g. `BiblioPixelAnimations.matrix` in documents.  "More stuff".

But we have already another mechanism to get rid of prefixes - the "resolution" mechanism that lets you say, `simpixel` instead of `bibliopixel.drivers.simpixel`.

So what I'm saying is 

1. to change this resolution so there is a _list_ of directories.

2. to add BiblioPixelAnimations to that list for animations

**Comment by adammhaile** [comment]
I'm fine with that. And it doesn't need to be a directory as they are
installed as a python module. And are guaranteed to be installed. So you
could just import BiblioPixel and then query that module for sub modules.

**Comment by estiens** [comment]
It might also be nice to have a `custom_animations` directory installed with one very well documented example of a python animation for bibliopixel. This could allow people an animation where they could play with altering parameters in a step function for example and see what they do.

It would also give them a directory to put custom animations in that would be loaded automatically so no need to do anything with a path or alias. (Put your own animation here and call it by putting custom_animations.YourCustomAnimation in a project file!)

I know you said you aren't really targeting developers any more with this (and no doubt there's other LED platforms out there for developers) but in my mind BP + and all_pixel is still some of the best and most cost effective out of the box functionality you can get for interfacing with just about any LED through a USB port.

And things like not really understanding why when I ran `bp run` from one directory my animation loaded fine, but from another directory it didn't work at all were significantly more difficult impediments to getting up and running with developing for bibliopixel. Not because they are hard problems, but just because they can be frustrating and make me feel like I don't know whether I'm fighting against a python issue here, a file system issue here, etc but I'm sure it's not anything complicated.

Or could be a CLI generator `bp create MyCustomAnimation` and it stubs out a basic animation in the correct path with the main functions that are called by BP (pre-run, step, etc) and is free to be altered.

**Comment by rec** [comment]
> I know you said you aren't really targeting developers any more with this

Oi!  Not so!

We are definitely targeting developers as we always have, but we _also_ are _trying_ to make it usable for people who are not developers.

I'd go even somewhat further and say, "We have almost zero user documentation, but the code is at least readable for developers, so they have an advantage".  :-D

In particular, we're aggressively moving towards the Project file being the only way to create a project, even if you are actually using bp within your own code.

---

Now, in terms of documenting _for_ developers, my claim is that the things that developers really need to know are:

1. How to write an animation 
2. How to write controls.
3. Other things you need to know to achieve those two - e.g. "how numpy works"
4. Maybe layouts.
