### ISSUE TITLE
REST multi controls don't work if changing animation index and current animation properties at same time

### ISSUE THREAD

**Issue by estiens** [ManiacalLabs/BiblioPixel#885]
REST multi controls work great if you are changing multiple properties on the current running animation.

However if you do something like `?animation.index=4&animation.animation.brightness=10` it doesn't pass that brightness value to the animation you are setting it too (but probably the last one).

Note, I don't know that there is any way around this, as the multi-control probably runs immediately and the animation doesn't switch immediately.

Perhaps what is needed instead is some kind of control that can say switch to this animation and pass in these values after you switch to it.

You can of course do slightly hacky things like switch to an animation, sleep for 10ms, then send your parameters you want for that animation. However, obviously hard to time exactly, can end up not passing them in because not running yet or passing them in and getting some kind of flicker.

**Comment by rec** [comment]
Oh, DAMN, that's a nasty one!  :-/  Gosh, you're really working this stuff out for me, aren't you?  :-)

This is obvious in hindsight.  :-D In fact, my guess is that for some systems, this might work - but _intermittently_.

Here's what's going on!

When that URL hits the server, those arguments are translated into a dictionary - `{animation.index: 4, animation.animation.brightness: 10}`...

So far so good, except that there are no guarantees as to the order of the entries in the dictionary.  (In fact, they seem to come in in alphabetic order, which explains why the first element goes to the end...)

And then each dictionary entry is translated into an Edit, which is put on a queue, so when I finally read these, I have no idea at all that these two entries were from the same update!

---

To fix this properly I need to fix #882 but I have a cheap fix right now.

I'm extracting the URL data - `animation.index=4&animation.animation.brightness=10` - as an unordered dictionary because that's the way that Flask naturally gives it to me.  

But I'm sure there's a way I can ask for the order, or even if it comes down to it parse the URL myself.

This will mean that the order in the queue is the order you specify in the URL

---

TBH, this is sorta bogus.  I feel it's a poor idea to depend on the order of parameters in a URL for information - but it's reliable, I can do it fast, and people will understand it easily enough.
