### ISSUE TITLE
`bp` should start up faster

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#932]
On a Pi Zero, the startup time was reported as 11.5s.

See the [users' group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/maniacal-labs-users/f7JV3qTJi24/WyoC6VduCwAJ).

**Comment by adammhaile** [comment]
WILLNOTFIX - This is due to a few things:
- The Pi Zero is SLOW - Can't fix this obviously.
 - The ARM Python interpreter is SLOW - Only thing we can do here is look
into precompiling everything to .pyc files on installation.... maybe?
Though, if that was the case then it would be faster the second time. The
major problem here is that bp is HUGE. Not really a complaint, as it does a
ton. But it has a million dependencies. I've run tools to print out
everything it's doing on load of even just `bp --help` and it's a lot. We
would really need to audit the code paths and make sure that things are
only being imported if they need to be but the current design of bp pretty
much ensures it imports nearly everything regardless of it needing it or
not.
- They are using a junk SD card. - I specifically buy UHS-1 class 10 cards
from Samsung because if this. I've personally seen a better SD card improve
bp load times over 200%

**Comment by rec** [comment]
Eh, I'll be an hour's worth of work would have a 50% chance of being able to speed up the load time by 50%.  :-D

But the real solution is only start up BP once and use `bp restart` to do your work.

**Comment by MyNameIsCosmo** [comment]
I've used `cProfile` and `snakeviz` to get a hint as to what's causing performance issues in Python scripts.
Usually it's imports and dependencies, as adam pointed out. Other times, it's just the hardware limitations.

```console
pip install snakeviz
python -m cProfile -o out.prof ./scripts/bp
snakeviz out.prof
```

Snakeviz will open a webpage that will display runtime data with different styles and a comprehensive listing of runtime and calls.

On my machine, running simply `bibliopixel` has a .438s runtime just to print the usage.
On one of the current projects I'm working on, I brought a ~.385s runtime to print the usage down to ~.007s by making sure dependencies of each command are loaded in the `run()` functions and are not included when the command module is loaded. I haven't done much profiling past this point.

(also: hey, what's up, long time no talk! I really want to start working with BP again, but life/work/[Murphy](https://en.wikipedia.org/wiki/Murphy%27s_law) has taken over)

**Comment by adammhaile** [comment]
Thanks for the suggestions. @rec I definitely think that for v4.0 we need
to bring the load time WAY down. The `bp` command loads way too much stuff
on start. We're just suffering from so much bloat since the v3.0 release.
It's good bloat, but we need to make it fast again.

**Comment by rec** [comment]
I'm closing this as too general, and we can open specifics later.

We have two strategies.  The first is to pull off functionality into completely separate commands!

For example, we now have a `bp-pid` script that replaces the old `bp restart` and also takes almost no time to start.

The second to late load a lot of our dependencies...
